# Generated by Django 5.0.4 on 2024-04-30 12:54

import apps.user.validators.username
import django.core.validators
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_20240317_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[apps.user.validators.username.username_validator, django.core.validators.RegexValidator('^[a-zA-Z0-9_-]+#[0-9]{4}$', message='Username is not valid for this regex `^[a-zA-Z0-9_-]+#[0-9]{4}$`')], verbose_name='username'),
        ),
    ]
